[metadata]
name = openruyi-precommit-hooks
version = 0.1.0
description = Some out-of-the-box hooks for pre-commit (openruyi edition).
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/openRuyi-Project/openruyi-precommit-hooks
author = redrose2100
license = MIT
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: Implementation :: CPython

[options]
packages = find:
install_requires =
    pyyaml>=6.0
python_requires = >=3.10

[options.packages.find]
exclude =
    tests*
    testing*

[options.entry_points]
console_scripts =
    check-spdx-header = openruyi_precommit_hooks.check_spdx_header:main

[bdist_wheel]
universal = True

[mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true

[mypy-testing.*]
disallow_untyped_defs = false

[mypy-tests.*]
disallow_untyped_defs = false
