# flake8: noqa: E501  -- spec file contents are reproduced verbatim
from __future__ import annotations

from pathlib import Path

import pytest

from openruyi_precommit_hooks.check_spdx_header import main

ISCAS = 'Institute of Software, Chinese Academy of Sciences (ISCAS)'
RUYI = 'openRuyi Project Contributors'

DEFAULT_ISCAS = f'# SPDX-FileCopyrightText: (C) 2026 {ISCAS}'
DEFAULT_RUYI = f'# SPDX-FileCopyrightText: (C) 2026 {RUYI}'
LICENSE_MULAN = '# SPDX-License-Identifier: MulanPSL-2.0'
SPEC_BODY = 'Name:           foo\nVersion:        1.0\n'


def _copyright(owner: str, years: str = '2026') -> str:
    """Build an SPDX-FileCopyrightText line for the given owner."""
    return f'# SPDX-FileCopyrightText: (C) {years} {owner}'


def _header(
    *,
    iscas: str | None = DEFAULT_ISCAS,
    ruyi: str | None = DEFAULT_RUYI,
    contributor: str | None = None,
    n_blank: int = 1,
    license_line: str | None = LICENSE_MULAN,
    body: str = SPEC_BODY,
) -> str:
    """Assemble a spec file from the given header pieces."""
    parts: list[str] = []
    if iscas is not None:
        parts.append(iscas)
    if ruyi is not None:
        parts.append(ruyi)
    if contributor is not None:
        parts.append(contributor)
    parts.extend(['#'] * n_blank)
    if license_line is not None:
        parts.append(license_line)
    return '\n'.join(parts) + '\n\n' + body


def _write(tmp_path: Path, name: str, content: str) -> str:
    p = tmp_path / name
    p.write_text(content, encoding='utf-8')
    return str(p)


@pytest.mark.parametrize(
    ('content', 'filename'),
    [
        pytest.param(
            _header(
                contributor='# SPDX-FileContributor: Your Name <your.email@example.com>',
            ),
            'good1.spec',
            id='with-contributor',
        ),
        pytest.param(
            _header(
                iscas=_copyright(ISCAS, '2025, 2026'),
                ruyi=_copyright(RUYI, '2025, 2026'),
            ),
            'good2.spec',
            id='without-contributor-multi-year',
        ),
        pytest.param(
            _header(
                iscas=_copyright(ISCAS, '2025-2026'),
                ruyi=_copyright(RUYI, '2025-2026'),
            ),
            'good3.spec',
            id='year-range',
        ),
    ],
)
def test_ok_header(tmp_path: Path, content: str, filename: str) -> None:
    retv = main([_write(tmp_path, filename, content)])
    assert retv == 0


@pytest.mark.parametrize(
    ('content', 'filename'),
    [
        pytest.param(_header(iscas=None), 'bad1.spec', id='missing-iscas'),
        pytest.param(_header(ruyi=None), 'bad2.spec', id='missing-ruyi'),
        pytest.param(
            _header(license_line='# SPDX-License-Identifier: Apache-2.0'),
            'bad4b.spec',
            id='wrong-license-with-blank-separator',
        ),
        pytest.param(_header(n_blank=0), 'bad7.spec', id='missing-blank'),
        pytest.param(_header(n_blank=2), 'bad8.spec', id='too-many-blank'),
        pytest.param(
            'Name:           foo\nVersion:        1.0\n', 'bad5.spec',
            id='no-comments-at-start',
        ),
        pytest.param('', 'bad6.spec', id='empty-file'),
        pytest.param(
            '# generated by openruyi-tooling\n' +
            _header(),
            'bad9.spec',
            id='plain-comment-before-spdx-block',
        ),
        pytest.param(
            '\n' + _header(),
            'bad10.spec',
            id='leading-blank-line',
        ),
        pytest.param(
            '# SPDX-FileCopyrightText: (C) 2026 Institute of Software, '
            'Chinese Academy of Sciences (ISCAS)\n'
            '# generated by openruyi-tooling\n'
            '# SPDX-FileCopyrightText: (C) 2026 openRuyi Project '
            'Contributors\n'
            '#\n'
            '# SPDX-License-Identifier: MulanPSL-2.0\n'
            '\n'
            'Name:           foo\nVersion:        1.0\n',
            'bad11.spec',
            id='non-spdx-comment-in-block',
        ),
        pytest.param(
            '# SPDX-FileCopyrightText: (C) 2026 Institute of Software, '
            'Chinese Academy of Sciences (ISCAS)\n'
            '# SPDX-FileCopyrightText: (C) 2026 openRuyi Project '
            'Contributors\n'
            '# some unrelated comment\n'
            '#\n'
            '# SPDX-License-Identifier: MulanPSL-2.0\n'
            '\n'
            'Name:           foo\nVersion:        1.0\n',
            'bad12.spec',
            id='non-spdx-comment-between-copyright-and-license',
        ),
    ],
)
def test_bad_header(tmp_path: Path, content: str, filename: str) -> None:
    retv = main([_write(tmp_path, filename, content)])
    assert retv == 1


def test_missing_license_identifier(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    content = _header(license_line=None)
    retv = main([_write(tmp_path, 'bad3.spec', content)])
    captured = capsys.readouterr()
    assert retv == 1
    assert 'missing required header line' in captured.out
    assert 'SPDX-License-Identifier: MulanPSL-2.0' in captured.out


def test_wrong_license_identifier(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    content = _header(license_line='# SPDX-License-Identifier: MIT')
    retv = main([_write(tmp_path, 'bad4.spec', content)])
    captured = capsys.readouterr()
    assert retv == 1
    # The license line exists but is not the default license; the message
    # must not claim the line is missing.
    assert 'missing required header line' not in captured.out
    assert 'must be the default license "MulanPSL-2.0"' in captured.out
    assert 'found "MIT"' in captured.out


def test_multiple_files_all_bad(tmp_path: Path) -> None:
    retv = main([
        _write(tmp_path, 'x1.spec', 'Name: a\n'),
        _write(tmp_path, 'x2.spec', 'Name: b\n'),
    ])
    assert retv == 1
