# flake8: noqa: E501  -- spec file contents are reproduced verbatim
from __future__ import annotations

from pathlib import Path

import pytest

from openruyi_precommit_hooks.check_spdx_header import _check_spdx_header
from openruyi_precommit_hooks.check_spdx_header import main

ISCAS = 'Institute of Software, Chinese Academy of Sciences (ISCAS)'
RUYI = 'openRuyi Project Contributors'

DEFAULT_ISCAS = f'# SPDX-FileCopyrightText: (C) 2026 {ISCAS}'
DEFAULT_RUYI = f'# SPDX-FileCopyrightText: (C) 2026 {RUYI}'
LICENSE_MULAN = '# SPDX-License-Identifier: MulanPSL-2.0'
SPEC_BODY = 'Name:           foo\nVersion:        1.0\n'


def _copyright(owner: str, years: str = '2026') -> str:
    """Build an SPDX-FileCopyrightText line for the given owner."""
    return f'# SPDX-FileCopyrightText: (C) {years} {owner}'


def _header(
    *,
    iscas: str | None = DEFAULT_ISCAS,
    ruyi: str | None = DEFAULT_RUYI,
    contributors: list[str] | None = None,
    n_blank: int = 1,
    license_line: str | None = LICENSE_MULAN,
    body: str = SPEC_BODY,
) -> str:
    """Assemble a spec file from the given header pieces."""
    parts: list[str] = []
    if iscas is not None:
        parts.append(iscas)
    if ruyi is not None:
        parts.append(ruyi)
    if contributors:
        parts.extend(contributors)
    parts.extend(['#'] * n_blank)
    if license_line is not None:
        parts.append(license_line)
    return '\n'.join(parts) + '\n\n' + body


def _write(tmp_path: Path, name: str, content: str) -> str:
    p = tmp_path / name
    p.write_text(content, encoding='utf-8')
    return str(p)


@pytest.mark.parametrize(
    ('content', 'filename'),
    [
        pytest.param(
            _header(
                contributors=[
                    '# SPDX-FileContributor: Your Name <your.email@example.com>',
                ],
            ),
            'good1.spec',
            id='with-contributor',
        ),
        pytest.param(
            _header(
                contributors=[
                    '# SPDX-FileContributor: Your Name <your.email@example.com>',
                    '# SPDX-FileContributor: Another Dev <another@example.com>',
                ],
            ),
            'good4.spec',
            id='with-multiple-contributors',
        ),
        pytest.param(
            _header(
                iscas=_copyright(ISCAS, '2025, 2026'),
                ruyi=_copyright(RUYI, '2025, 2026'),
            ),
            'good2.spec',
            id='without-contributor-multi-year',
        ),
        pytest.param(
            _header(
                iscas=_copyright(ISCAS, '2025-2026'),
                ruyi=_copyright(RUYI, '2025-2026'),
            ),
            'good3.spec',
            id='year-range',
        ),
    ],
)
def test_ok_header(tmp_path: Path, content: str, filename: str) -> None:
    errors = _check_spdx_header(_write(tmp_path, filename, content))
    assert errors == []


@pytest.mark.parametrize(
    ('content', 'expected_substrings'),
    [
        pytest.param(
            _header(iscas=None),
            ['missing required header line', 'Institute of Software'],
            id='missing-iscas',
        ),
        pytest.param(
            _header(ruyi=None),
            ['missing required header line', 'openRuyi Project Contributors'],
            id='missing-ruyi',
        ),
        pytest.param(
            _header(license_line='# SPDX-License-Identifier: Apache-2.0'),
            ['must be the default license "MulanPSL-2.0"', 'found "Apache-2.0"'],
            id='wrong-license-with-blank-separator',
        ),
        pytest.param(
            _header(n_blank=0),
            ['missing required blank "#" comment line'],
            id='missing-blank',
        ),
        pytest.param(
            _header(n_blank=2),
            ['there must be exactly one blank "#" comment line'],
            id='too-many-blank',
        ),
        pytest.param(
            'Name:           foo\nVersion:        1.0\n',
            ['file does not start with a comment'],
            id='no-comments-at-start',
        ),
        pytest.param(
            '',
            ['file is empty'],
            id='empty-file',
        ),
        pytest.param(
            '# generated by openruyi-tooling\n' + _header(),
            ['file must start with SPDX declarations', '# generated by openruyi-tooling'],
            id='plain-comment-before-spdx-block',
        ),
        pytest.param(
            '\n' + _header(),
            ['file must not start with a blank line'],
            id='leading-blank-line',
        ),
        pytest.param(
            '# SPDX-FileCopyrightText: (C) 2026 Institute of Software, '
            'Chinese Academy of Sciences (ISCAS)\n'
            '# generated by openruyi-tooling\n'
            '# SPDX-FileCopyrightText: (C) 2026 openRuyi Project '
            'Contributors\n'
            '#\n'
            '# SPDX-License-Identifier: MulanPSL-2.0\n'
            '\n'
            'Name:           foo\nVersion:        1.0\n',
            [
                'header may only contain SPDX declarations',
                '# generated by openruyi-tooling',
            ],
            id='non-spdx-comment-in-block',
        ),
        pytest.param(
            '# SPDX-FileCopyrightText: (C) 2026 Institute of Software, '
            'Chinese Academy of Sciences (ISCAS)\n'
            '# SPDX-FileCopyrightText: (C) 2026 openRuyi Project '
            'Contributors\n'
            '# some unrelated comment\n'
            '#\n'
            '# SPDX-License-Identifier: MulanPSL-2.0\n'
            '\n'
            'Name:           foo\nVersion:        1.0\n',
            [
                'header may only contain SPDX declarations',
                '# some unrelated comment',
            ],
            id='non-spdx-comment-between-copyright-and-license',
        ),
        pytest.param(
            DEFAULT_ISCAS + '\n' + DEFAULT_ISCAS + '\n' + DEFAULT_RUYI +
            '\n#\n' + LICENSE_MULAN + '\n\n' + SPEC_BODY,
            ['duplicate ISCAS copyright line'],
            id='duplicate-iscas-copyright',
        ),
        pytest.param(
            DEFAULT_ISCAS + '\n' + DEFAULT_RUYI + '\n' + DEFAULT_RUYI +
            '\n#\n' + LICENSE_MULAN + '\n\n' + SPEC_BODY,
            ['duplicate openRuyi copyright line'],
            id='duplicate-ruyi-copyright',
        ),
        pytest.param(
            DEFAULT_ISCAS + '\n' + DEFAULT_RUYI + '\n#\n' +
            LICENSE_MULAN + '\n' + LICENSE_MULAN + '\n\n' + SPEC_BODY,
            ['duplicate SPDX-License-Identifier line'],
            id='duplicate-license-line',
        ),
        pytest.param(
            '# SPDX-FileContributor: Your Name <your.email@example.com>\n' +
            DEFAULT_ISCAS + '\n' + DEFAULT_RUYI + '\n#\n' +
            LICENSE_MULAN + '\n\n' + SPEC_BODY,
            ['header lines are out of order'],
            id='contributor-before-copyright',
        ),
        pytest.param(
            DEFAULT_ISCAS + '\n' +
            '# SPDX-FileContributor: Your Name <your.email@example.com>\n' +
            DEFAULT_RUYI + '\n#\n' + LICENSE_MULAN + '\n\n' + SPEC_BODY,
            ['header lines are out of order'],
            id='contributor-between-copyrights',
        ),
        pytest.param(
            DEFAULT_ISCAS + '\n' + DEFAULT_RUYI + '\n#\n' +
            '# SPDX-FileContributor: Your Name <your.email@example.com>\n' +
            LICENSE_MULAN + '\n\n' + SPEC_BODY,
            ['header lines are out of order'],
            id='contributor-between-blank-and-license',
        ),
        pytest.param(
            DEFAULT_ISCAS + '\n' + DEFAULT_RUYI + '\n#\n' +
            LICENSE_MULAN + '\n' +
            '# SPDX-FileContributor: Your Name <your.email@example.com>\n' +
            '\n' + SPEC_BODY,
            ['header lines are out of order'],
            id='contributor-after-license',
        ),
    ],
)
def test_bad_header(
    tmp_path: Path, content: str, expected_substrings: list[str],
) -> None:
    errors = _check_spdx_header(_write(tmp_path, 'bad.spec', content))
    assert errors != []
    joined = '\n'.join(errors)
    for expected in expected_substrings:
        assert expected in joined


def test_missing_license_identifier(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    content = _header(license_line=None)
    retv = main([_write(tmp_path, 'bad3.spec', content)])
    captured = capsys.readouterr()
    assert retv == 1
    assert 'missing required header line' in captured.out
    assert 'SPDX-License-Identifier: MulanPSL-2.0' in captured.out


def test_wrong_license_identifier(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    content = _header(license_line='# SPDX-License-Identifier: MIT')
    retv = main([_write(tmp_path, 'bad4.spec', content)])
    captured = capsys.readouterr()
    assert retv == 1
    # The license line exists but is not the default license; the message
    # must not claim the line is missing.
    assert 'missing required header line' not in captured.out
    assert 'must be the default license "MulanPSL-2.0"' in captured.out
    assert 'found "MIT"' in captured.out


def test_main_exit_code_and_output(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    """main() should return non-zero and print every error for bad files."""
    paths = [
        _write(tmp_path, 'ok.spec', _header()),
        _write(tmp_path, 'bad1.spec', _header(iscas=None)),
        _write(tmp_path, 'bad2.spec', _header(ruyi=None)),
    ]
    retv = main(paths)
    captured = capsys.readouterr()
    assert retv == 1
    assert 'bad1.spec' in captured.out
    assert 'bad2.spec' in captured.out
    assert 'ok.spec' not in captured.out


def test_main_empty_input() -> None:
    assert main([]) == 0


def test_main_unreadable_file(tmp_path: Path) -> None:
    missing = tmp_path / 'missing.spec'
    retv = main([str(missing)])
    assert retv == 1


def test_main_bad_utf8(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    p = tmp_path / 'bad-utf8.spec'
    p.write_bytes(b'# SPDX-FileCopyrightText: (C) 2026 \xff\xfe\n')
    retv = main([str(p)])
    captured = capsys.readouterr()
    assert retv == 1
    assert 'not valid UTF-8' in captured.out


def test_main_all_bad_prints_each(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    """Each bad file should produce at least one output line."""
    paths = [
        _write(tmp_path, 'x1.spec', 'Name: a\n'),
        _write(tmp_path, 'x2.spec', 'Name: b\n'),
    ]
    retv = main(paths)
    captured = capsys.readouterr()
    assert retv == 1
    assert 'x1.spec' in captured.out
    assert 'x2.spec' in captured.out
